---
title: "Progress review report"
subtitle: "Advances in Artificial Intelligence for Data Visualization: Automate Reading of Diagnostic Plots with Compute Vision Models"
output: pdf_document
date: "2023-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

This is a temporary document. It perhaps needs to be transferred to a templated document. 

keywords:
AI, data visualization, residual plot, visual inference, hypothesis testing, computer vision

# Overview of the thesis

1. background and motivation
- the role of visual diagnostics in modelling

Model diagnostics are important steps to validate model assumptions, examine goodness of fit and reveal uncaptured structure by the model. When diagnosing model, though numeric summaries are mostly available and some are even endorsed by finite or asymptotic properties, graphical representation of data is still preferred, or at least needed by data analysts, due to its intuitiveness and the possibility for unexpected discoveries which may be abstract and unquantifiable. For example, in regression diagnostics, it is common to plot residuals versus fitted values as the starting point of investigating the adequacy of the fit and checking the underlying assumptions.


- a brief introduction to visual inference




- limitation of lineup protocol



2. research questions
-  a. study the use of visual inference in regression diagnostics with a comparison to conventional test
-  b. build a computer vision system to evaluate residual plot
-  c. make the system available to the public
3. summarise the work in the first year
- an experiment to compare visual test with conventional test 
- a prototype model for lineup evaluation
- points out the limitation of the work
4. summarise the work in the second year
- refine and reconduct the experiment
5. main findings to date
- findings from the first year
- findings from the second year

# Thesis structure

topic

chapter 1: Introduction

chapter 2
the first paper

chapter 3
build a computer vision system to evaluate residual plot

chapter 4?
software publication

chapter 5
discussion and future work

# Timetable

- April: submit abstract to ASC
- May: submit paper
- June: submit poster/short paper to IEEE vis conf, start working on computer vision model
- July: leave for few weeks
- Aug
- Sep: finalize the computer vision model
- Oct: IEEE vis conf
- Nov: web interface development 
- Dec: ASC

- Jan, 2024: 
- Feb, 2024: 
- Mar, 2024: submit paper
- Aug, 2024: submit thesis  

# Difficulties

things that are actually quite serious

1. identified difficulties
2. suggestions for overcoming these difficulties
