---
title: "Untitled"
output: html_document
date: '2022-06-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(visage)
library(tidyverse)
```

# N: 50

Sigma: 0.5

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 0.5)
ori_dat <- mod$gen(50)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 1

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 1)
ori_dat <- mod$gen(50)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 2

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 2)
ori_dat <- mod$gen(50)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 4

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 4)
ori_dat <- mod$gen(50)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

# N: 100

Sigma: 0.5

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 0.5)
ori_dat <- mod$gen(100)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 1

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 1)
ori_dat <- mod$gen(100)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 2

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 2)
ori_dat <- mod$gen(100)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 4

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 4)
ori_dat <- mod$gen(100)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

# N: 300

Sigma: 0.5

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 0.5)
ori_dat <- mod$gen(300)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 1

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 1)
ori_dat <- mod$gen(300)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 2

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 2)
ori_dat <- mod$gen(300)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```

Sigma: 4

```{r fig.height=6, fig.width=8, cache = TRUE}
mod <- poly_model(2, x = rand_uniform(-1, 1), sigma = 4)
ori_dat <- mod$gen(300)
i <- 0
plot_list <- list()

for (shape in c(1, 2, 3, 4)) {

  i <- i + 1
  mod$set_prm("shape", shape) %>%
    {.$gen(50, computed = select(ori_dat, x, e))} %>%
    {mod$plot(., remove_axis = TRUE, remove_grid_line = TRUE, theme = theme_light())} +
    ggtitle(glue::glue("shape:{shape}")) -> plot_list[[i]]

} 

patchwork::wrap_plots(plot_list)
```
