# Introduction {#sec-intro}

This is where you introduce the main ideas of your thesis, and an overview of the context and background.

In a PhD, Chapter 2 would normally contain a literature review. Typically, Chapters 3--5 would contain your own contributions. Think of each of these as potential papers to be submitted to journals. Finally, Chapter 6 provides some concluding remarks, discussion, ideas for future research, and so on. Appendixes can contain additional material that don't fit into any chapters, but that you want to put on record. For example, additional tables, output, etc.

This thesis explores innovative approaches to regression model diagnostics across three chapters. Chapter 2 presents evidence from a visual inference experiment using the lineup protocol to demonstrate why plotting residuals is superior to conventional numerical hypothesis tests for model diagnosis. The lineup protocol provides a more reliable and consistent method for interpreting residual plots, avoiding the oversensitivity of conventional tests while detecting a range of departures from good residuals simultaneously.

Chapter 3 introduces a computer vision model to automate the assessment of residual plots, addressing the scalability limitations of human-based visual inference. This model is trained to predict a distance measure based on Kullback-Leibler divergence, quantifying the disparity between the residual distribution of a fitted classical normal linear regression model and the reference distribution. Simulation studies show that the computer vision model strikes a balance between conventional tests and human visual tests in terms of sensitivity, though it is slightly less effective on non-linearity patterns.

Chapter 4 describes the development of an R package that implements the computer vision model for automated assessment of residual plots. The package includes a shiny app for ease of use, allowing analysts to input a sample of residuals and receive predictions of visual signal strength (VSS) along with supporting information to assist in diagnosing model fit. This tool aims to bridge the gap between the need for effective diagnostics and the limitations of conventional tests and human effort.
