project:
  type: book

execute:
  keep-md: true

book:
  title: "Advances in Artificial Intelligence for Data Visualization: Developing Computer Vision Models to Automate Reading of Data Plots, with Application to Regression Diagnostics"
  author: "Weihao Li"
  repo-url: https://github.com/TengMCing/PhD
  repo-subdir: Thesis
  repo-actions: [edit]
  repo-branch: master
  downloads: [pdf]
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "abstract.qmd"
    - "acknowledgements.qmd"
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "03-chap3.qmd"
    - "04-chap4.qmd"
    - "05-chap5.qmd"
    - "refs.qmd"
  appendices:
    - "A-appA.qmd"
    - "B-appB.qmd"
    - "C-appC.qmd"
  sidebar:
    style: "docked"

bibliography: thesisrefs.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2024
affiliation: Department of Econometrics & Business Statistics
degrees: 'B.Comm. (Hons), Monash University'

format:
  monashthesis-html: default
  monashthesis-pdf:
    shorttitle: "Advances in Artificial Intelligence for Data Visualization"
    link-citations: true
    include-in-header:
      - text: |
          \usepackage{pmboxdraw}
