---
title: |
  Taylor & Francis Rmarkdown template for authors (\LaTeX\-based 
  \textsf{Interact} layout + Chicago author-date reference style)
type: ARTICLE TEMPLATE
author:
  - name: Weihao Li
    affil: a
    email: weihao.li@monash.edu
  - name: John Smith
    affil: b
    email: john.smith@uni-freiburg.de
  - name: Dominik Leutnant
    affil: c, \dagger, \ddagger
    email: leutnant@fh-muenster.de
affiliation:
  - num: a
    address: |
      Taylor & Francis, 4 Park Square, Milton Park, Abingdon, UK
  - num: b
    address: |
      Institut für Informatik, Albert-Ludwigs-Universität, Freiburg, Germany
  - num: c
    address: |
      Muenster University of Applied Sciences - 
      Institute for Infrastructure, Water, Resources, Environment,
      Correnstr. 25, 48149 Münster, Germany
bibliography: interactcadsample.bib
abstract: |
  This template is for authors who are preparing a manuscript for a Taylor & 
  Francis journal using the \LaTeX\ document preparation system and the 
  `interact} class file, which is available via selected journals' home 
  pages on the Taylor & Francis website.
keywords: |
  Sections; lists; figures; tables; mathematics; fonts; references; appendices
header-includes: |
  \usepackage{hyperref}
  \usepackage[utf8]{inputenc}
  \def\tightlist{}
output: rticles::tf_article
---

problem: residual plot diagnostics
conventional test: too sensitive

background: 

<!-- week 1 -->
1. residual plot for model diagnostics

a. residual is widely used
b. what are the types of residual plots
c. comparison

<!-- week 2 -->
2. conventional test: F, BP
3. visual test: lineup, theory

<!-- week 4 -->
desc of experiment:
1. simulation setup
2. experimental design
3. result

<!-- week 3 -->
comparison of conventional tests:
1. power (visual test vs. conventional test)
(visual test most different one (everything test, any departure))
2. investigate the difference (gap), give examples
3. conventional is too sensitive
4. make conventional less sensitive (vary alpha)


<!-- last week -->
conclusion:
1. too sensitive, visual test is needed/preferable
2. visual test is infeasible in large scale (expensive)
3. future work (role of computer vision)


Title: 



# Introduction

Diagnostics of the classical normal linear regression model conventionally involve evaluating the fitness of the proposed model, detecting the presence of influential observations and outliers, checking the validity of model assumptions and many more. Tools such as summary statistics, hypothesis testing, and data plots are essential for a systematic and detailed examination of the regression model [@mansfield1987diagnostic].

## Data plots

Data plots are one of the most important and preferred methods of regression diagnostics. Graphical summaries in which residuals are plotted against fitted values or other functions of the predictor variables that are approximately orthogonal to residuals are refereed to as standard residual plots. They are commonly used to identify patterns which are indicative of nonconstant error variance or nonlinearity [@cook1982residuals]. Raw residuals and studentized residuals are the two most frequently used residuals in standard residual plots. The debt on which type of residuals should be used always present. While raw residuals are the most common output of computer regression software package, by applying a scaling factor, the ability of revealing nonconstant error variance in standard residual plots will often be enhanced by studentized residuals in small sample size [@gunst2018regression]. 

As a two-dimensional representation of a model in a $p$-dimensional space, standard residual plots project  data points onto the variable of the horizontal axis, which is a vector in $p$-dimensional space. Observations with the same projection will be treated as equivalent as they have the same position of the abscissa. Therefore, standard residual plots are often useful in revealing model inadequacies in the direction of the variable of the horizontal axis, but could be inadequate for detecting patterns in other directions, especially in those perpendicular to the variable of the horizontal axis. Hence, in practice, multiple standard residual plots with different horizontal axes will be examined.


<!-- large sample size-->
Overlapping data points is a general issue in scatter plots not limited to standard residual plots, which often makes plots difficult to interpret because visual patterns are concealed. Thus, for relatively large sample size, @cleveland1975graphical suggests the use of robust moving statistics as reference lines to give aids to eye in seeing patterns, which nowadays, are usually replaced with a spline or local polynomial regression line.

Other types of data plots that are often used in regression diagnostics include partial residual plots and probability plots. Partial residual plots are useful supplements to standard residual plots as they provide additional information on the direction of linearity as well as the nonlinearity of each predictor. Probability plots can be used to compare the sampling distribution of the residuals to the normal distribution.

## Hypothesis testing




